# Generated by Django 2.0.4 on 2018-04-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('date_modified', models.DateField()),
            ],
        ),
    ]
