# Generated by Django 2.0.4 on 2018-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_modified',
            field=models.DateField(null=True),
        ),
    ]
